### ISSUE TITLE
is this intended to be a pure npm scripts powered version of patternlab? <eom>

### ISSUE THREAD

**Issue by cdaringe** [pattern-lab/edition-node#1]
clearly still in work :)

**Comment by bmuenzenmeyer** [comment]
hi @cdaringe sorta - in conjuction with a CLI that is being worked on

**Comment by raphaelokon** [comment]
Hi there. I made really good progress on the CLI. Just sorting tests and hopefully we will have an alpha next week.

**Comment by cdaringe** [comment]
🎲 🎲 🎲 🎲 🎲 
yahtzee!
