### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by getsetbro** [pattern-lab/edition-node#5]
I did:
1. git clone https://github.com/pattern-lab/edition-node.git
2. npm install
3. npm run build

I got:

Pattern Lab Node v3.0.0-alpha.7
Pattern Engine mustache: good to go
Incremental builds enabled.
WARNING: missing or malformed ./source/_data/listitems.json file.  Pattern Lab may not work without this file.
Could not find pattern referenced with partial syntax README.md. This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a different template or within data as a link.
{ Error: ENOENT: no such file or directory, open '/Users/gsb/Documents/github/patternlab.io-bulma/public/dependencyGraph.json'
…

**Comment by whatjackhasmade** [comment]
Same issue here!

**Comment by shirintag** [comment]
I have the same issue.
WARNING: missing or malformed ./source/_data/listitems.json file.  Pattern Lab may not work without this file.
Could not find pattern referenced with partial syntax README.md. This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a different template or within data as a link.

**Comment by TheTravisM** [comment]
Is there any update to this?

**Comment by getsetbro** [comment]
This repo has moved to the pattern-lab/patternlab-node monorepo!

Future development should be built off of https://github.com/pattern-lab/patternlab-node

This repo will be archived in the near future.
